## postgres data source configuration
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=postgres
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/postgres
quarkus.datasource.jdbc.driver=org.postgresql.Driver

## milvus data source configuration
milvus.uri=http://localhost:19530
milvus.collection.name=demo_ai_documents
milvus.collection.floatVector.dim=384

# langchain4j model for chat
quarkus.langchain4j.openai.timeout=250s
quarkus.langchain4j.openai.base-url=http://localhost:1144/v1
quarkus.langchain4j.openai.api-key=dummy
quarkus.langchain4j.openai.chat-model.model-name=granite4.2
quarkus.langchain4j.openai.chat-model.max-tokens=8192

# langchain4j model for embeddings
quarkus.langchain4j.openai.granite.base-url=http://localhost:1145/v1
quarkus.langchain4j.openai.granite.api-key=dummy
quarkus.langchain4j.openai.granite.embedding-model.model-name=granite

# langchain4j milvus embeddings configuration
quarkus.langchain4j.milvus.host=localhost
quarkus.langchain4j.milvus.port=19530
quarkus.langchain4j.milvus.create-collection=false
quarkus.langchain4j.milvus.collection-name=demo_ai_documents
quarkus.langchain4j.milvus.devservices.enabled=false
quarkus.langchain4j.milvus.primary-field=id
quarkus.langchain4j.milvus.vector-field=vector
quarkus.langchain4j.milvus.dimension=384


quarkus.banner.enabled=false
quarkus.devservices.enabled=false
quarkus.log.console.enable=false
quarkus.log.level=OFF

#quarkus.log.category."io.mosfet".level=DEBUG
#quarkus.langchain4j.openai.log-requests=true
#quarkus.langchain4j.openai.log-responses=true
#quarkus.log.category."dev.langchain4j".level=DEBUG
#quarkus.log.category."io.quarkiverse.langchain4j".level=DEBUG