= JBang Catalog for Debezium


image:https://img.shields.io/github/license/openshift/origin.svg?maxAge=2592000["Licensed under Apache License version 2.0", link="https://www.apache.org/licenses/LICENSE-2.0"]
image:https://img.shields.io/badge/zulip-join_chat-brightgreen.svg["Chat on Zulip", link="https://debezium.zulipchat.com"]


This repository hosts **Catalog of JBang Scripts & Templates for Debezium**, enabling an easy way to work with Debezium for change data capture (CDC) and related patterns.

== Requirements

Depending on the extension and target (JVM vs native), typical prerequisites include:

- JDK 21+
- https://www.jbang.dev/documentation/jbang/latest/installation.html#installation-methods[Jbang 0.132.1]
- Docker/Podman for local services


== Quick start

Add the Jbang Catalog to your system using **jbang**:

```bash
jbang catalog add debezium
```

download a template for a datasource like **postgres** with `capturing:datasource`:

```bash
jbang init -t capturing:postgres@debezium debezium.java
```

== Available templates

You can find templates for the following datasources:

- postgres
- mysql
- mongodb
- sql server
- mariadb

== License

This software is licensed under the terms you may find in the file named `LICENSE.txt` in this directory.