quarkus.log.level=WARN
quarkus.banner.enabled=false
quarkus.native.additional-build-args=--initialize-at-run-time=org.apache.commons.compress.compressors.brotli.BrotliCompressorInputStream,--initialize-at-run-time=org.apache.http,--initialize-at-run-time=com.github.luben.zstd